### PR TITLE
Fixes double rendering issue when re-entering room #49

### LINKED ISSUE #49: The second call causes double-overlayed Video Streams on the person's device that first joined the room
Summary: When attempting to make a second call to a different room than before the user who first connects to the room has both streams rendered in his main window: local and remote

### How to reproduce

- This test uses two rooms: zebra and dolphin (you can name them whatever you want)
- Authenticate on both devices
- Have both users join the room "zebra"
- Once the second person joins both will receive each other's video feed
- Disconnect the call on one device
- The call is automatically disconnected on the other device as well (both disconnect from the room)
- Now one device connects to the room "dolphin"
- The second device joins that room as well
- The call is established and both can see each others video streams
- **Problem**: The first person that joined the room, receives two overlaying streams in his main window: His local stream and the remote stream. In my case the double-overlayed stream occurs on the device that first connected to the room

### Video recording of how it looks

https://youtu.be/AbdT6snUUds

### Devices used for the test:
- Google Pixel with Android 7.1.1
- Asus Nexus Tablet with Android 6.1
- Sony Xperia Z5 Compact (in combination with Google Pixel) with Android 6.x

Let me know if you need more information. I managed to reproduce this issue each time, following above steps.

### PR DESCRIPTION
**Pull request by aaalaniz**
This PR fixes #49. We were not handling participant video tracks correctly. Now the remote participant's video track is added `onConnected` and `onVideoTrackAdded`

### CODE REVIEW

File: quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java [hunk 1]
```diff
@@ -270,35 +267,70 @@ private void addParticipant(Participant participant) {
...
          */
         participant.getMedia().setListener(mediaListener());
     }
 
     /*
+     * Set primary view as renderer for participant video track
+     */
+    private void addParticipantVideo(VideoTrack videoTrack) {
+        moveLocalVideoToThumbnailView();
+        primaryVideoView.setMirror(false);
```
Comment (AgentKnopf) [inline quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java]: Could there be a problem if moveLocalVideoToThumbnailView does nothing (because Visible == View.VISIBLE) and you still execute the other steps in this method?

Comment (aaalaniz) [inline quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java]: It just prevents moving the local video to thumbnail twice. Are you seeing any other additional issues?

Comment (AgentKnopf) [inline quickstart/src/main/java/com/twilio/video/quickstart/activity/VideoActivity.java]: No, should be okay :)

**Comment by idelgado** [comment]
👍
